apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ldap-config
  namespace: $VAR_NAMESPACE
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: $MY_FILE_LDAP_STORAGE_CLASS
  volumeMode: Filesystem
