apiVersion: v1
metadata:
  name: pvc-ldap-config
kind: PersistentVolumeClaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: $MY_FILE_LDAP_STORAGE_CLASS
  volumeMode: Filesystem
