apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: openldap-scc
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowedCapabilities: ["NET_BIND_SERVICE"]
defaultAddCapabilities: []
priority: 10
readOnlyRootFilesystem: true
requiredDropCapabilities: ["ALL"]
volumes: ["configMap", "emptyDir", "persistentVolumeClaim", "projected", "secret"]