apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: ${VAR_ES_INSTANCE_NAME}
    eventstreams.ibm.com/cluster: ${VAR_ES_INSTANCE_NAME}
  name: kafka-user1
  namespace: ${VAR_ES_NAMESPACE}
spec:
  authentication:
    type: tls
  authorization:
    acls:
    - host: '*'
      operations:
      - Read
      - Write
      - Create
      resource:
        name: '*'
        patternType: literal
        type: topic
    - host: '*'
      operations:
      - Read
      - Alter
      resource:
        name: __schema_
        patternType: prefix
        type: topic
    - host: '*'
      operations:
      - Read
      resource:
        name: '*'
        patternType: literal
        type: group
    - host: '*'
      operations:
      - Write
      resource:
        name: '*'
        patternType: literal
        type: transactionalId
    type: simple