apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  labels:
        eventstreams.ibm.com/cluster: ${VAR_ES_KAFKA_CONNECT_INSTANCE_NAME}
  name: mq-sink
  namespace: $VAR_ES_NAMESPACE
spec:
  class: com.ibm.eventstreams.connect.mqsink.MQSinkConnector
  tasksMax: 1
  config:
    mq.queue.manager: $VAR_QMGR_UC
    mq.channel.name: $VAR_CHL_UC
    mq.connection.name.list: ${VAR_QMGR}-ibm-mq(1414)
    mq.ssl.truststore.location: /tmp/kafka/cluster.truststore.p12
    mq.ssl.truststore.password: Fxfj6ANTCNFzdrN-fpdeqZ6W-M_ZxD2W
    mq.ssl.cipher.suite: TLS_AES_256_GCM_SHA384
    mq.ssl.truststore.type: PKCS12
    mq.queue: FROM.KAFKA
    mq.user.name: ""
    mq.password: ""
    mq.message.body.jms: "false"
    mq.time.to.live: "10800000"
    topics: LH.ORDERS
    mq.persistent: "true"
    mq.connection.mode: client
    mq.message.builder: com.ibm.eventstreams.connect.mqsink.builders.DefaultMessageBuilder
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter