apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: europe
  name: image-puller-binding
subjects:
  - kind: ServiceAccount
    name: mm2-mirrormaker2
    namespace: europe
roleRef:
  kind: Role
  name: image-puller
  apiGroup: rbac.authorization.k8s.io