apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: europe
  name: image-puller
rules:
  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreams", "imagestreamtags"]
    verbs: ["get", "list", "watch", "create"]