apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: rename
  namespace: europe
spec:
  runPolicy: "Serial"
  source:
    type: dockerfile
    dockerfile: |
      FROM cp.icr.io/cp/ibm-eventstreams-kafka@sha256:cb5da87bb8341a3134c36ac43ed686a7a724d20dcbc9d3f15b4e322550af3801
      USER root
      COPY rename.topic-1.0.jar  /opt/kafka/libs/
      USER 1001
  strategy:
    type: Docker
    dockerStrategy:
    from:
      kind: DockerImage
      name: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:cb5da87bb8341a3134c36ac43ed686a7a724d20dcbc9d3f15b4e322550af3801
    pullSecret:
      name: ibm-entitlement-key
  output:
    to:
      kind: ImageStreamTag
      name: rename:1.0
      namespace: europe