apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rename_pvc
  namespace: europe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem