apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: ${VAR_ES_INSTANCE_NAME}
    app.kubernetes.io/instance: ${VAR_ES_INSTANCE_NAME}
  name: ${VAR_ES_TOPIC_NAME}
  namespace: ${VAR_ES_NAMESPACE}
spec:
  config:
    min.insync.replicas: "1"
    retention.ms: "86400000"
  partitions: ${VAR_ES_SPEC_TOPIC_PARTITION}
  replicas: ${VAR_ES_SPEC_TOPIC_REPLICA}
  topicName: ${VAR_ES_SPEC_TOPIC_NAME}