apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: es-all-access
  namespace: ${VAR_ES_NAMESPACE}
  labels:
    eventstreams.ibm.com/cluster: ${VAR_ES_INSTANCE_NAME}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations: ["Create","Read","Write","Describe"]  # Now an array under 'operations'
      - resource:
          type: topic
          name: __schema_
          patternType: prefix
        operations: ["Read","Alter"]  # Now an array under 'operations'
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations: ["Read"]  # Now an array under 'operations'
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations: ["Read"]  # Now an array under 'operations'
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operations: ["Write"]  # Now an array under 'operations'
