apiVersion: platform.confluent.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-connect-credentials
  namespace: $VAR_CONFLUENT_NAMESPACE
  labels:
    eventstreams.ibm.com/cluster: ${VAR_CONFLUENT_INSTANCE_NAME}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    # permission to consume and produce to any topic
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - Write
          - Read
          - Create
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - Read
    type: simple