apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  name: ${VAR_ACE_INTEGRATIONRUNTIME_NAME}
  namespace: ${VAR_ACE_NAMESPACE}
spec:
  license:
    accept: true
    license: ${MY_ACE_LIC}
    use: ${MY_ACE_LIC_USAGE}
  flowType:
    toolkitFlow: true
    designerAPIFlow: true
    designerEventFlow: true
  routes:
    disabled: false
  service:
    type: NodePort
  template:
    spec:
      containers:
      - name: runtime
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
  barURL: 
    - ${VAR_ACE_BAR_URL}
  version: ${MY_ACE_VERSION}
  replicas: 1
  logFormat: basic
  configurations: 
    - ${VAR_ACE_SERVERCONF_NAME}
    - ${VAR_ACE_BARAUTH_NAME}
