apiVersion: v1
kind: ConfigMap
metadata:
  name: sb1-mqsc-cm
  namespace: cp4i
data:
  sb1.mqsc: |+
    *
    * setup queue
    *

    * the queue that JMS apps will put to and get from
    DEFINE QLOCAL(COMMANDS) REPLACE


    *
    * setup channels
    *

    * create the channel that JMS apps will use
    DEFINE CHANNEL(APP.SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE


    *
    * setup security
    *

    * JMS apps will use the APP channel
    SET CHLAUTH(APP.SVRCONN) TYPE(BLOCKUSER) USERLIST(*MQUSER) WARN(YES) ACTION(REPLACE)

    REFRESH SECURITY

    * the JMS apps can do whatever they want to
    SET AUTHREC OBJTYPE(QMGR) GROUP('mqusers') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('**') GROUP('mqusers') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(CHANNEL) PROFILE('**') GROUP('mqusers') AUTHADD(ALL)
