apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: sb1
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
    use: "NonProduction"
  terminationGracePeriodSeconds: 30
  pki:
    keys:
      - name: sb1
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: sb1-secret
    trust:
      - name: sb1
        secret:
          secretName: sb1-secret
          items:
            - ca.crt
  securityContext:
    initVolumeAsRoot: false
  queueManager:
    name: SB1
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    route:
      enabled: true
    storage:
      defaultClass: ocs-storagecluster-ceph-rbd
      queueManager:
        deleteClaim: true
        type: persistent-claim
    availability:
      type: SingleInstance
      updateStrategy: RollingUpdate
    imagePullPolicy: IfNotPresent
    debug: false
    logFormat: Basic
    mqsc:
      - configMap:
          name: sb1-mqsc-cm
          items:
            - sb1.mqsc
      - configMap:
          name: sb1-ldap-cm
          items:
            - sb1.ldap
  version: 9.4.2.0-r1
  template:
    pod:
      containers:
        - name: qmgr
          resources: {}
  web:
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
    enabled: true