apiVersion: stepzen-graph.ibm.com/v1beta1
kind: StepZenGraphServer
metadata:
  name: ${VAR_APIC_GRAPHQL_INSTANCE_NAME}
  namespace: ${VAR_APIC_GRAPHQL_NAMESPACE}
spec:
  license:
    accept: true
  controlDatabaseSecret: ${MY_APIC_GRAPHQL_DSN_SECRET}
#  imagePullSecrets:
#    - ibm-entitlement-key  
  graphServer:
    hpa:
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
  graphServerSubscription:
    hpa:
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      