apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${VAR_CERT}
  namespace: ${VAR_MQ_NAMESPACE}
spec:
  commonName: "${VAR_COMMON_NAME}"
  dnsNames:
    - "${VAR_SAN_DNS}"
  duration: 8760h
  issuerRef:
    name: ${VAR_QMGR}-issuer
    kind: Issuer
  privateKey:
    algorithm: RSA
    size: 2048
  renewBefore: 720h
  secretName: ${VAR_CERT}-secret
  subject:
    organizations:
      - "${MY_LDAP_ORGANISATION}"
    organizationalUnits:
      - "${MY_LDAP_ORGANISATION}_MQ"
  usages:
    - server auth
    - client auth
