apiVersion: v1
kind: ServiceAccount
metadata:
  name: datapower-nano-operator
  namespace: ${VAR_NANO_GATEWAY_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datapower-nano-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gateways
      - httproutes
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses/status
      - gateways/status
      - httproutes/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - nano.datapower.ibm.com
    resources:
      - apis
      - assemblies
      - autoscaleconfigs
      - jwtproviders
      - managements
      - oauthproviders
      - runtimeconfigs
      - runtimes
      - tlsclientprofiles
      - tlsserverprofiles
      - userdefinedpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nano.datapower.ibm.com
    resources:
      - apis/status
      - assemblies/status
      - autoscaleconfigs/status
      - jwtproviders/status
      - managements/scale
      - managements/status
      - oauthproviders/status
      - runtimeconfigs/status
      - runtimes/scale
      - runtimes/status
      - tlsclientprofiles/status
      - tlsserverprofiles/status
      - userdefinedpolicies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datapower-nano-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datapower-nano-operator
subjects:
  - kind: ServiceAccount
    name: datapower-nano-operator
    namespace: ${VAR_NANO_GATEWAY_NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapower-nano-operator
  namespace: ${VAR_NANO_GATEWAY_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datapower-nano-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datapower-nano-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - env:
            - name: RUST_LOG
              value: dpn_operator=info
            - name: RUST_BACKTRACE
              value: "1"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ${MY_CP_IO_IMAGE_REGISTRY}/datapower/datapower-nano-operator:build.248@sha256:a09a2c497fa96347dc667c513818e1e60110f6e4ebd2b08aff5cef74be16e0b3
          imagePullPolicy: Always
          name: datapower-nano-operator
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      imagePullSecrets:
        - name: ${DEFAULT_IMAGE_PULL_SECRET}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: datapower-nano-operator
      terminationGracePeriodSeconds: 10
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: datapower-nano-operator
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
