apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: $MY_OPERATOR_NAME
  namespace: $MY_OPERATORS_NAMESPACE
spec:
  channel: stable
  installPlanApproval: Manual
  name: instana-agent-operator
  source: $MY_CATALOG_SOURCE_NAME
  #sourceNamespace: openshift-marketplace
  #startingCSV: instana-agent-operator.v2.0.10
