apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  name: $VAR_OPERATOR_NAME
  namespace: $VAR_NAMESPACE
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
spec:
  channel: $VAR_OPERATOR_CHL
  installPlanApproval: $VAR_STRATEGY
  name: $VAR_OPERATOR_NAME
  source: $VAR_CATALOG_SOURCE_NAME
  sourceNamespace: $MY_CATALOGSOURCES_NAMESPACE