apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: $VAR_OPERATOR_NAME
  namespace: $VAR_OPERATOR_NAMESPACE
  labels:
    backup.integration.ibm.com/component: subscription    
spec:
  channel: $VAR_OPERATOR_CHL
  installPlanApproval: $VAR_STRATEGY
  name: $VAR_OPERATOR_NAME
  source: $VAR_CATALOG_SOURCE_NAME
  sourceNamespace: $MY_CATALOGSOURCES_NAMESPACE
  startingCSV: $MY_STARTING_CSV

