apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: $MY_OPERATOR_NAME
  namespace: $MY_OPERATOR_NAMESPACE
spec:
  channel: $MY_CURRENT_CHL
  installPlanApproval: $MY_STRATEGY
  name: $MY_OPERATOR_NAME
  source: $MY_CATALOG_SOURCE_NAME
  sourceNamespace: $MY_CATALOGSOURCES_NAMESPACE