apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: datagen-host
  annotations:
    eventstreams.ibm.com/use-connector-resources: 'true'
spec:
  config:
    group.id: connect-group
    client.id: connect-client
    config.storage.topic: connect-configs
    offset.storage.topic: connect-offsets
    status.storage.topic: connect-status
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
  bootstrapServers: '${MY_ES_INSTANCE_NAME}-kafka-bootstrap.${es_project}.svc:9093'
  resources:
    limits:
      cpu: 2048m
      memory: 2Gi
    requests:
      cpu: 2048m
      memory: 2Gi
  authentication:
    certificateAndKey:
      certificate: user.crt
      key: user.key
      secretName: kafka-user1
    type: tls      
  template:
    buildConfig:
      pullSecret: ibm-entitlement-key
    connectContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
    pod:
      imagePullSecrets: []
      metadata:
        annotations:
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          productVersion: 11.3.1
          productID: 2a79e49111f44ec3acd89608e56138f5
          cloudpakName: IBM Cloud Pak for Integration
          productChargedContainers: datagen-host-connect
          productCloudpakRatio: '2:1'
          productName: IBM Event Streams for Non Production
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productMetric: VIRTUAL_PROCESSOR_CORE
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: ${MY_ES_INSTANCE_NAME}-cluster-ca-cert
  replicas: 1
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/${es_project}/datagen-producer:0.0.6
    plugins:
      - name: datagen
        artifacts:
          - type: jar
            url: https://github.com/IBM/kafka-connect-loosehangerjeans-source/releases/download/0.0.6/kafka-connect-loosehangerjeans-source-0.0.6-jar-with-dependencies.jar