apiVersion: v1
kind: ConfigMap
metadata:
  name: $VAR_AUTH_CM
  namespace: $VAR_MQ_NAMESPACE
data:
  ${VAR_QMGR}.auth: |
    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(OPTIONAL)
    SET CHLAUTH(${VAR_QMGR_UC}CHL) TYPE(SSLPEERMAP) SSLPEER('CN=${MY_USER}') USERSRC(MAP) MCAUSER('${MY_USER}') ACTION(ADD)
    SET AUTHREC PRINCIPAL('${MY_USER}') OBJTYPE(QMGR) AUTHADD(ALL)
    SET AUTHREC PROFILE('Q1') PRINCIPAL('${MY_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT,DSP)
    SET AUTHREC PROFILE('Q2') PRINCIPAL('${MY_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)
    SET AUTHREC PROFILE('PAYMT.REQ.CPY') PRINCIPAL('${MY_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)
    SET AUTHREC PROFILE('FROM.KAFKA') PRINCIPAL('${MY_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)
    SET AUTHREC PROFILE('SYSTEM.ADMIN.COMMAND.QUEUE') PRINCIPAL('${MY_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)
    SET AUTHREC PROFILE('SYSTEM.MQSC.REPLY.QUEUE') PRINCIPAL('${MY_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)