apiVersion: v1
kind: ConfigMap
metadata:
  name: $VAR_AUTH_CM
  namespace: $VAR_MQ_NAMESPACE
data:
  ${VAR_QMGR}.auth: |
    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(OPTIONAL)
    SET CHLAUTH(${VAR_QMGR_UC}CHL) TYPE(SSLPEERMAP) SSLPEER('CN=${VAR_MQ_USER}') USERSRC(MAP) MCAUSER('${VAR_MQ_USER}') ACTION(ADD)
    * Define the user here
    SET AUTHREC PRINCIPAL('${VAR_MQ_USER}') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ,SETALL) 
    SET AUTHREC PROFILE('Q1') PRINCIPAL('${VAR_MQ_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT,DSP)
    SET AUTHREC PROFILE('Q2') PRINCIPAL('${VAR_MQ_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)
    SET AUTHREC PROFILE('PAYMT.REQ.CPY') PRINCIPAL('${VAR_MQ_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)
    SET AUTHREC PROFILE('FROM.KAFKA') PRINCIPAL('${VAR_MQ_USER}') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT)