apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${VAR_CERT}                        # ${VAR_QMGR}-cert
  namespace: ${VAR_NAMESPACE}              # $VAR_MQ_NAMESPACE
spec:
  commonName: "${VAR_COMMON_NAME}"
  dnsNames:
    - "${VAR_SAN_DNS}"
  duration: 17520h
  renewBefore: 720h
  issuerRef:
    kind: Issuer
    name: ${VAR_ISSUER}
  secretName: ${VAR_SECRET}                 # ${VAR_QMGR}-secret
  secretTemplate:
    labels:
      app.kubernetes.io/component: ${VAR_LABEL}
  subject:
    organizations:
      - ${MY_LDAP_ORGANISATION}
    countries:
      - ${MY_LDAP_COUNTRY}
    localities:
      - ${MY_LDAP_LOCALITY}
    provinces:
      - ${MY_LDAP_STATE}