apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: ${mq_instance_name}-qm1
  namespace: $mq_project
  finalizers:
    - finalizer.queuemanagers.mq.ibm.com
spec:
  license:
    accept: true
    license: $mq_license
    metric: VirtualProcessorCore
    use: NonProduction
  tracing:
    enabled: false
    namespace: $mq_project
  web:
    enabled: true
  version: $mq_version
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  queueManager:
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
    availability:
      type: SingleInstance
      updateStrategy: RollingUpdate
    name: QM1
    storage:
      defaultClass: $my_block_storage_class
      persistedData:
        enabled: false
      queueManager:
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false  
    securityContext:
     supplementalGroups: [99]
  web:
    enabled: true