apiVersion: v1
kind: ConfigMap
metadata:
  name: ${QMGR}-mqsc-cm
  namespace: $MY_OC_PROJECT
data:
  ${QMGR}.mqsc: |
    DEFINE QLOCAL('Q1') REPLACE DEFPSIST(YES)
    DEFINE QLOCAL('TO.KAFKA') REPLACE DEFPSIST(YES) 
    DEFINE QLOCAL('FROM.KAFKA') REPLACE DEFPSIST(YES) 
    DEFINE CHANNEL('${QMGR_UC}CHL') CHLTYPE(SVRCONN) REPLACE TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH('${QMGR_UC}CHL') TYPE(BLOCKUSER) USERLIST(NOBODY) ACTION(ADD)
