apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${QMGR}-root-cert
  namespace: ${MY_OC_PROJECT}
spec:
  commonName: ${QMGR}-root-cert
  dnsNames:
    - "${QMGR}-ibm-mq.${MY_OC_PROJECT}.svc.cluster.local"
  duration: 17520h0m0s
  isCA: true
  issuerRef:
    kind: Issuer
    name: ${QMGR}-issuer
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
    size: 2048
  renewBefore: 720h0m0s
  secretName: ${QMGR}-secret
  secretTemplate:
    labels:
      app.kubernetes.io/component: ${QMGR}-label1
  usages:
  - server auth
  - client auth