apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $QMGR
  namespace: $MY_OC_PROJECT
spec:
  license:
    accept: true
    license: $MY_MQ_LIC
    use: "NonProduction"
  pki:
    keys:
      - name: $QMGR
        secret:
          secretName: ${QMGR}-secret
          items:
            - tls.key
            - tls.crt
  queueManager:
    name: $QMGR_UC
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: ephemeral
    availability:
      type: SingleInstance
    mqsc:
      - configMap:
          name: ${QMGR}-mqsc-cm
          items:
            - ${QMGR}.mqsc   
  version: $MY_MQ_VERSION
  web:
    enabled: true
