apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $QMGR
  namespace: $OC_PROJECT
spec:
  license:
    accept: true
    license: $MY_MQ_LIC
    use: NonProduction
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
  queueManager:
    availability:
      type: SingleInstance
    storage:
      queueManager:
        type: ephemeral
    name: $QMGR
  version: $MY_MQ_VERSION