apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: $operator_name
  namespace: $operators_project
spec:
  channel: $current_channel
  name: $operator_name
  source: $catalog_source_name
  sourceNamespace: $my_oc_cs_ns