kind: ConfigMap
apiVersion: v1
metadata:
  name: $VAR_JWKS_CM
  namespace: $VAR_MQ_NAMESPACE
data:
  ${VAR_QMGR}.ini: |-
    Service:
      Name=AuthorizationService
      EntryPoints=14
      SecurityPolicy=UserExternal
    SSL:
     HTTPSKeyStore=/etc/mqm/jwks/jwks.p12
    JWKS:
     issuername=https://keycloak-ibm-common-services.apps.678f772ff501a868a5829095.ocp.techzone.ibm.com/realms/cloudpak
     Endpoint=https://keycloak-ibm-common-services.apps.678f772ff501a868a5829095.ocp.techzone.ibm.com/realms/cloudpak/protocol/openid-connect/certs
     UserClaim=client_id