apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devportal-admin-client
  namespace: ${VAR_APIC_NAMESPACE}
  labels: {
    app.kubernetes.io/instance: "management",
    app.kubernetes.io/managed-by: "ibm-apiconnect",
    app.kubernetes.io/name: "devportal-admin-client"
  }
spec:
  subject:
    organizations:
    - cert-manager
  commonName: devportal-admin-client
  secretName: devportal-admin-client
  issuerRef:
    name: ingress-issuer
  usages:
  - "client auth"
  - "signing"
  - "key encipherment"
  duration: 17520h # 2 years
  renewBefore: 720h # 30 days
  privateKey:
    rotationPolicy: Always
  secretTemplate:
    labels:
      app.kubernetes.io/instance: "management"
      app.kubernetes.io/managed-by: "ibm-apiconnect"
      app.kubernetes.io/name: "devportal-admin-client"