apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${VAR_CERT}
  namespace: ${VAR_NAMESPACE}
spec:
  commonName: "${VAR_COMMON_NAME}"
  dnsNames:
    - "${VAR_SAN_DNS}"
  duration: 8760h
  issuerRef:
    kind: Issuer
    name: ${VAR_ISSUER}
  privateKey:
    algorithm: RSA
    size: 2048
  renewBefore: 720h
  secretName: ${VAR_SECRET}
  secretTemplate:
    labels:
      app.kubernetes.io/component: ${VAR_LABEL}
  subject:
    organizations:
      - "${MY_LDAP_ORGANISATION}"
    organizationalUnits:
      - "${MY_LDAP_ORGANISATION}_MQ"
  usages:
    - server auth
    - client auth
