kind: ConfigMap
apiVersion: v1
metadata:
  name: mainmqm-mqsc
data:
  mainmqm.mqsc: |
    DEF QLOCAL(LQ.PAYM.PROC.REQ) REPLACE
    DEF QLOCAL(AQ.PAYM.PROC.RSP) REPLACE
    DEF QLOCAL(LQ.DEMO) REPLACE
    DEFINE TOPIC(TP.PAYM.EVT) TOPICSTR(PAYMEVT) REPLACE
    DEFINE QALIAS(AQ.PAYM.EVT) TARGET(TP.PAYM.EVT) TARGTYPE(TOPIC) REPLACE
    DEF QLOCAL(LQ.SUB.PAYM.EVT) REPLACE
    DEFINE SUB(SUB.PAYM.EVT) TOPICSTR(PAYMEVT) DEST(LQ.SUB.PAYM.EVT) REPLACE

    DEFINE QLOCAL(LQ.DEMO.STREAM) DEFPSIST(YES) REPLACE
    DEFINE QLOCAL(LQ.DEMO.ERROR) DEFPSIST(YES) REPLACE
    DEFINE QLOCAL(LQ.DEMO.API) BOQNAME(LQ.DEMO.ERROR) BOTHRESH(1) STREAMQ(LQ.DEMO.STREAM) STRMQOS(MUSTDUP) REPLACE
    DEFINE QLOCAL(LQ.DEMO.EVENT) BOQNAME(LQ.DEMO.ERROR) BOTHRESH(1) REPLACE

    DEF QLOCAL (DLQ)

    ALTER QMGR DEADQ(DLQ)

    DEF CHANNEL (CL.PAYMENTS) CHLTYPE(SVRCONN) MCAUSER('mqm')
    DEF CHANNEL (CL.DEMO) CHLTYPE(SVRCONN) MCAUSER('mqm')
    DEF CHANNEL (CL.ES) CHLTYPE(SVRCONN) MCAUSER('mqm')

    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(NONE) CHCKLOCL(NONE) 

    SET CHLAUTH(*) TYPE(BLOCKUSER) USERLIST(*MQADMIN) ACTION(REMOVE)

    REFRESH SECURITY TYPE(CONNAUTH) 

    REFRESH SECURITY TYPE(AUTHSERV)
