apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $MY_MQ_INSTANCE_NAME
  namespace: $MY_MQ_PROJECT
spec:
  license:
    accept: true
    license: $MY_MQ_LIC
    use: NonProduction
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
  queueManager:
    name: $mq_qmgr_name
    availability:
      type: $mq_availability_type
    storage:
      queueManager:
        type: persistent-claim
        class: $MY_BLOCK_STORAGE_CLASS
        size: 2Gi
      defaultClass: $MY_BLOCK_STORAGE_CLASS
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    route:
      enabled: true
    mqsc:
      - configMap:
          name: $mq_qmgr_name-mqsc
          items:
            - $mq_qmgr_name.mqsc
  version: $MY_MQ_VERSION
