apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $MY_MQ_INSTANCE_NAME
  namespace: $MY_MQ_PROJECT
spec:
  license:
    accept: true
    license: $MY_MQ_LIC
    use: NonProduction
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
  queueManager:
    name: $MY_MQ_INSTANCE_NAME
    availability:
      type: SingleInstance
    storage:
      queueManager:
        type: ephemeral
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    route:
      enabled: true
  version: $MY_MQ_VERSION
