apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: $my_cp_apic_instance_name
  namespace: $my_oc_project
spec:
  analytics:
    storage:
      enabled: true
      type: unique
  endpointTypes:
    - APIs
    - Events
  imagePullSecrets:
    - ibm-entitlement-key
  imageRegistry: cp.icr.io/cp/apic
  license:
    accept: true
    license: $my_ibm_cp_apic_license
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  profile: $my_ibm_cp_apic_profile
  storageClassName: ibmc-block-gold
  version: $my_ibm_cp_apic_version
