apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $my_cp_mq_instance_name
  namespace: $my_oc_project
spec:
  license:
    accept: true
    license: $my_ibm_cp4i_license
    use: NonProduction
  tracing:
    enabled: false
    namespace: $my_oc_project
  web:
    enabled: true
  version: $my_ibm_cp_mq_version
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  queueManager:
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
        
    name: QUICKSTART
    availability:
      type: NativeHA
      updateStrategy: RollingUpdate
    storage:
      defaultClass: ibmc-file-gold-gid
      queueManager:
        class: ibmc-file-gold-gid
        deleteClaim: true
        type: persistent-claim
