# This is what was used as a parameter when provisioning the cluster

# This is based on the namespace and instance name, this is used for Topic creation

VAR_CONFLUENT_INSTANCE_NAME="confluent"
VAR_CONFLUENT_NAMESPACE="iwhi-confluent"
