apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: cp4i-es
  namespace: cp4i
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
spec:
  version: latest
  license: 
    license: L-QYVA-B365MB
    accept: true
    use: CloudPakForIntegrationNonProduction
  strimziOverrides:
    entityOperator:
      topicOperator: {}
    kafka:
      replicas: 3
      config:
        auto.create.topics.enable: 'false'
        inter.broker.protocol.version: '3.8'
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
        default.replication.factor: 3
        min.insync.replicas: 3
      authorization:
        type: simple
      listeners:
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: cp4i-prod-3-brokers-metrics-config
      storage:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
        size: 20Gi
    zookeeper:
      replicas: 1
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: cp4i-prod-3-brokers-metrics-config
      storage:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
        size: 20Gi
  adminApi: {}
  adminUI:
     authentication:
       - type: scram-sha-512
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  security:
    internalTls: TLSv1.2