apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ace-is
  namespace: ${MY_OC_PROJECT}
spec:
  license:
    accept: true
    license: ${MY_ACE_LIC}
    use: ${MY_ACE_LIC_USAGE}
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  adminServerSecure: false
  barURL: ${MY_ACE_BAR_URL}
  router:
    timeout: 120s
  designerFlowsOperationMode: all
  designerFlowsType: event-driven-or-api-flows
  service:
    endpointType: http
  version: ${MY_ACE_VERSION}
  replicas: 1
  logFormat: basic
  configurations: 
    - ${MY_ACE_SERVERCONF_NAME}
    - ${MY_ACE_BARAUTH_NAME}
