apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: ace-barauth
  namespace: ${MY_OC_PROJECT}
spec:
  secretName: ${MY_ACE_BARAUTH_SECRET_NAME}
  version: ${MY_ACE_VERSION}
  type: barauth