apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: $VAR_POSTGRES_CLUSTER
  namespace: $VAR_POSTGRES_NAMESPACE
spec:
  instances: 1
  storage:
    size: 1Gi
  image: quay.io/enterprisedb/postgresql:15  # Use PostgreSQL 15 image or compatible
  postgresql:
    parameters:
      shared_buffers: "128MB"
      max_connections: "100"
  bootstrap:
    initdb:
      database: $VAR_POSTGRES_DATABASE
      owner: $VAR_POSTGRES_USER
      secret:
        name: $VAR_POSTGRES_SECRET
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            size: 1Gi
