apiVersion: v1
kind: Secret
metadata:
  name: cp4imq-secret
  namespace: cp4i
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVVQ0ZCczhHSkRJTGZKa2twUUhJRVk1VDVjOGVPeTVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1Cd3gKR2pBWUJnTlZCQU1URVdOekxXTmhMV05sY25ScFptbGpZWFJsTUI0WERUSTBNRFV4TlRBM01qTXlORm9YRFRJNQpNRFV4TkRBM01qTXlORm93V2pFTE1Ba0dBMVVFQmhNQ1JsSXhEREFLQmdOVkJBZ01BMGxFUmpFT01Bd0dBMVVFCkJ3d0ZVRUZTU1ZNeEVEQU9CZ05WQkFvTUIwSkZUa0ZEU0VreERUQUxCZ05WQkFzTUJGTkJRVVF4RERBS0JnTlYKQkFNTUEzTnlkakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNalhkWDhBd1NGSAptK2hpWjBtZW9TQjAxQzVlTTJES3FOTi9udFNNcjU4OGU5cVdiT2djQThFVkgzZERIMkNiZmNLWHpUZExGeFIvCmRHUDBxNEVSVWtFKzdaaVhQTW1qc0ViVTlYV0hSR2tVd3kzcWtJR1lDeVVyS1RjcDM0YnA0Rm1IeTlRVUplRUcKcjY0a3JlM2tTQmkzcklzK2duSmNVQlVsa3hwUDhOTk5tWWtXTjJKRVJPc3lXc1o1YnpsR2puZ3hza3NDY3dRUQptNWV0TjdQdks3czZhWi9ZOW1mK3BlNVRuNEdhTFpUbkF1MTd6OUVkN0RRb0VnQmNkeTRLSVNtMUxVSzQ4anRXCk4zRDVxVlZVLzNTSFhSWGRzdmpGM1Z5OFQzRi80d2ZjNHZiWE5SdEhiOUF1VzZPMWVFOGRpTGFmd1BLT1NlbVkKWVE5dy80cE5VMU1DQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFESk94T2N0RjBpUTh3WDJ5Y0xzZwpPdzBRUll3Zm1aRTdGSXVnOXRkZUYwZWpPeHo3d2lMeUVSd1BPYVZOSjdEV2cxVjBYOTVxWnBNelFFekZFc012CmVLTk1CTkJPb0dORlYzcGhBV21FTUNXQUhEbVU3cm1OK2x1cUdCOUo2OEVwR3hRQjJPOG1YZzFYaUxKc09mV1AKSjRnOTFxVk5pOTZwN2VXQU90QnhJcnl1SDNvK2FyU0s1dW01YmdCUkdIK1c2RnBZbjhxRFlscXUwSXBSd0VMUgp0a0tncG1wOWNNVTBYaklkeE03dTh2YjlmTFMwYmhBV2RMaGtsTHZLSVcrQms0ZXR0RkZwWVZ2NHZSdjlOVU9qCjQ2YUZpWEdGMnJJSk1FVEpGcGNZbGp5Znhxa3p3ZCs2MExHQ25rQkdWT3VuTTcvM0lmd1RIMkR2cGk4TDhGNGsKYmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREkxM1YvQU1FaFI1dm8KWW1kSm5xRWdkTlF1WGpOZ3lxalRmNTdVaksrZlBIdmFsbXpvSEFQQkZSOTNReDlnbTMzQ2w4MDNTeGNVZjNSago5S3VCRVZKQlB1MllsenpKbzdCRzFQVjFoMFJwRk1NdDZwQ0JtQXNsS3lrM0tkK0c2ZUJaaDh2VUZDWGhCcSt1CkpLM3Q1RWdZdDZ5TFBvSnlYRkFWSlpNYVQvRFRUWm1KRmpkaVJFVHJNbHJHZVc4NVJvNTRNYkpMQW5NRUVKdVgKclRlejd5dTdPbW1mMlBabi9xWHVVNStCbWkyVTV3THRlOC9SSGV3MEtCSUFYSGN1Q2lFcHRTMUN1UEk3VmpkdworYWxWVlA5MGgxMFYzYkw0eGQxY3ZFOXhmK01IM09MMjF6VWJSMi9RTGx1anRYaFBIWWkybjhEeWprbnBtR0VQCmNQK0tUVk5UQWdNQkFBRUNnZ0VBUlhyRUd2dVgxSHVCWkJNbXlFRW9YS0lPQlR4eGFicXlUUGlKYWQ2Qm93UzUKbEJVVjkvWTVGa0xJYittNG9TTXBqbmdWZGx0ejBKT0hJRTAwUjZKR1ltdnlwaWNyMEZYZ1ZhQzJpY0lSMklobQpQU3c0Y1p5M3ZsUUFIaVZPUHM0SjN1OHJoR0t6OS9Ub01jWmVwVDJqODJrWE45U1lMQmZqWEcxelJsY0JhUmVCCnBWTGVYcHVWaVNHVEQ5dTdtcmdaTkVqbFdVVFNQNEdMS3lYeWRFTU9hZXZONWtZeS92Tk0wdDE2Q1h4Y0N4YTcKZDRiY3BjTHZpOFZTeWM4SG5ydkxkU0xPY0ZkSUlEVzVkbU45UktZOHJyNTd4QkcrdTh0Q2dRK1BzbDNHalRVRwpiZmZPcFNYUUkxTXgwam5IV3NIc1FJTXZkSUtzSHNUSnNUMjBHMmR2QVFLQmdRRDY0alhzbHB2dGN2WTl5RVIvCkRITllsZW16ekhWUldxdklWMTBpNGxVL3Z3UWMxRkszTVVWWFc0TVJ5dVJYYThUTXNtenpuSTBEUThkemFlYXIKeEhwWWxGQ0tuREowTUpOYjFQYVU5eDhBQ1lpRUd5d1A1akNsRUVYdDJ4TmtZRlFXYmZac2x2K0drRVFxdGZoQwpVb3FHQ3BzQlloZHhLK285SENSTkFZU0dXUUtCZ1FETTcvNXIxeHVPNFV6MU94cWMwUUdZdjJPMUh0MlR5c1lWCkRNK29IL0pxcWhOWCtRRmF6QSsyTkdSZkJpRkUwcjdGNExNM2VuekwzZVVQMzV1M3ZzdlVVUEQ0YmhnQzdQbloKMkwvVTNQODkzd2sxRnJtTjluZWNQMEFzYzJkVjRaUEhRdnN5eC9xMVM4MEwxTnQwUTZhZnBCTmg1TTlkVk9LZQpNUURDSmpGSml3S0JnRC81djFaOWNYV3pneWR1RWtsem0xWlRwQ3k5VG8xWVdjWFV3V05MNUFGRmJIOE5oYXBCClhqVlFtTFBJMFVHWnNhMmhNamRORElod21FUE9GWXhucGV0QXB1a3h1NHYxZHg1THlEVmtidnRMY3d4OUFWZHMKazZzRDQxRXNORjI4VXJVRmhYbGJaLzJnZkVHSDlhNno3YThRdFVZOUJVMU9yWVMzMEdueW9TREJBb0dCQUlybwo2YVVqS3hUUDlpQUxMZUM1Y3NHY2lQTU50dGNrak50YjBhMTk2ZzBPdHduY1NHVEpDS1ZTSWU2ZTh4SDVYMEkxCktvVWlTMURNV1NWSFJmOW9IalVOb0Noa1IzWkVOcDdJNGs1Z2RjbjBVZ05nSWVudDgraytuanNEQmpvYUt0YlgKdWZrVHdBWC9HVDg1eW42bUZGMEZFL1k0NTYyMWlkMzhEUzJNUWNBOUFvR0JBTTQ2Mk5KNm0vMjI1Um92SE9OaApoMzZhRFFmeGlQZCs5akRRUzJFS3FzZjJEOVlJNE45dzRPTFFKWmZ0ckdqNDhJeXhmSGUybTNWblNnQzBjYUxCCkcrOExBZDlkNy94YlVkdmtTTzRQL1JyYnRnTWpoQkhIYm1HTEdlVXlhNGVIa2tVcHdlK0FGNE9pVGJWZ3cwYW4KWmtwYnVkRzBHOWVLU1dlRzdyeUVpVVltCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lSQUttcExsWkhnYnM2a1p5KzNjTFdqR2d3RFFZSktvWklodmNOQVFFTEJRQXcKSERFYU1CZ0dBMVVFQXhNUlkzTXRZMkV0WTJWeWRHbG1hV05oZEdVd0hoY05NalF3TlRBMk1qSXhNakV6V2hjTgpNall3TlRBMk1qSXhNakV6V2pBY01Sb3dHQVlEVlFRREV4RmpjeTFqWVMxalpYSjBhV1pwWTJGMFpUQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNQ0VlUVNEbEZZbWF0aEwvZDFNai9WSUQ3UFIKUDBJVklSU0xoWFlhU3VEOWxYb3RiczNOWXlCWDFzRWJueHdzbjBCNDVpWG85aFJrNkNpa0swNFBmbUU5ckNCMgpsTjBTNG5XSlZDd1gxRWdRSHpvdkhhRGpZK3Y0RUdWUFNCR21MVDlpb1lzTjNEaWNGQmpNYTJzSnFxRm9xSk11CkRmaEJjdnVQYmJISUVlNGo2cTREb0R2U2ZSNUl2ZkpWOGplMWgxeFh1TDlCdjF6TlpobG5VbkVJbFJuU0l0M0kKemp3VGdudUpYOC9zQ2lTNlQ4NlNsUkExWEFlUXRlbVNJMy8wWDJMVVZYSnFHM1h4YWlBVU1vL1ZvK3hsTkU3dQowcjgxdXBqdG9aaXVnL2RhZWFycWRNU2VGTzZKak5qOGR0UEtYd1d4Q0k4d1UwcTNxMDdXandpRVdkTUNBd0VBCkFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUUKRk5rdHVDMTUvV2dtcGsxU01NUTBqdXdNRU44ME1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXZQSmF4bFJyNgpLREx3b1BCdmtYeDNDUGFvUUQvUGpUQ2IrT0FyeG5GcHoxd2ZEVUFNcjVLenlPcCt1WEk5NlE3RWRNc29EcUx0ClBmMkxqeEVKT2Q1SW5xeWFQM0FyaXBBWDRKalhNQnozeldxTTFZSmlyV2kzUm9rU2dzM3BuVVlpOEt3RmpXT0QKTnZoeHQ1TzFLMGNacU5tT2NWc01MNTNySC8yVTc1Vk9kcW9iYzRXTnlSeGVOWjBtRlJWQ3ZQaVA3ck1WYWtuaApBSTRpaDgvbnp6dzRWNTFlUnArY0Y3VFFvdCtXazBmQlVhcCtUSWR6YkdNZWNWdWN6S25mZk5jN1h4R0dGN01ICnlrKzNLbGp6UEs3TkFyZnJTRVNSOEhHUHl4K1VGVnhmL3lkZEFyYkVpaStRbVlSb1pLVWQ3N3YvdlZUekVUNFkKTkhTZUtNaEJ6SndwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
type: kubernetes.io/tls
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cp4imq-route
  namespace: cp4i
spec:
  host: cp4imqchl.chl.mq.ibm.com
  to:
    kind: Service
    name: cp4imq-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cp4imq-mqsc-cm
  namespace: cp4i
data:
  cp4imq.mqsc: |
    DEFINE QLOCAL('Q1') REPLACE DEFPSIST(YES) 
    DEFINE CHANNEL('CP4IMQCHL') CHLTYPE(SVRCONN) REPLACE TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH('CP4IMQCHL') TYPE(BLOCKUSER) USERLIST(NOBODY) ACTION(ADD)
---
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: cp4imq
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: "NonProduction"
  pki:
    keys:
      - name: cp4imq
        secret:
          secretName: cp4imq-secret
          items:
            - tls.key
            - tls.crt
  queueManager:
    name: CP4IMQ
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: ephemeral
    availability:
      type: SingleInstance
    mqsc:
      - configMap:
          name: cp4imq-mqsc-cm
          items:
            - cp4imq.mqsc   
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.3.5.1-r1
  web:
    enabled: true
