apiVersion: v1
kind: ConfigMap
metadata:
 name: common-service-maps
 namespace: kube-public
data: 
 common-service-maps.yaml: |
   namespaceMapping:
   - requested-from-namespace:
     - $my_oc_project
     map-to-common-service-namespace: ${my_oc_project}-fs
   defaultCsNs: ibm-common-services