apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  name: common-service
  namespace: ${my_oc_project}-fs
spec:
  installPlanApproval: Automatic
  size: starterset
  manualManagement: true
  BYOCACertificate: false
  license:
    accept: true	
  storageClass: $my_block_storage_class
  features:
    bedrockshim:
      enabled: true
  services:
  - name: ibm-iam-operator
    spec:
      authentication:
        config:
          defaultAdminUser: cp4iuser
          bootStrapUserId: clusteradmin
          roksEnabled: true
          roksURL: 'https://c100-e.eu-de.containers.cloud.ibm.com:32301'
          roksUserPrefix: 'IAM#'
          oidcIssuerURL: 'https://c100-e.eu-de.containers.cloud.ibm.com:443/oidc/endpoint/OP'
          preferredLogin: DEFAULT,LDAP,SAML,ROKS
      oidcclientwatcher: {}
      pap: {}
      policycontroller: {}
      policydecision: {}
      secretwatcher: {}
      securityonboarding: {}
  - name: ibm-commonui-operator
    spec:
      globalUIConfig:
        enterpriseLDAP: 'reserve pour LDAP'
        defaultAuth: 'reserve pour defaultAuth'
        osAuth: 'reserve pour osAuth'
        enterpriseSAML: 'reserve pour SAML'