apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: ${MY_KEYCLOAK_NAMESPACE}
spec:
  dnsNames:
  - keycloak.apps.${MY_CLUSTER_DOMAIN}
  isCA: true
  secretName: ${MY_KEYCLOAK_TLS_SECRET}
  issuerRef:
    name: ${MY_ISSUER}
    kind: Issuer
