apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: ${MY_KEYCLOAK_NAME}
  namespace: ${MY_KEYCLOAK_NAMESPACE}
spec:
  instances: 1
#  externalAccess:
#    enabled: true
#    tlsSecret: ${MY_KEYCLOAK_TLS_SECRET}  # Secret managed by cert-manager
  db:
    vendor: postgres
    host: ${MY_POSTGRES_HOSTNAME} # an example "${VAR_POSTGRES_CLUSTER}-rw.${MY_POSTGRES_NAMESPACE}.svc.cluster.local"
    usernameSecret:
      name: ${MY_KEYCLOAK_DB_SECRET}
      key: username
    passwordSecret:
      name: ${MY_KEYCLOAK_DB_SECRET}
      key: password
  http:
    tlsSecret: ${MY_KEYCLOAK_TLS_SECRET} # Secret managed by cert-manager
  hostname:
    hostname: keycloak.apps.${MY_CLUSTER_DOMAIN}