# https://access.redhat.com/solutions/7007648
apiVersion: v1
kind: Secret
metadata:
  name: $MY_LOKI_SECRET
  namespace: $MY_LOGGING_NAMESPACE
stringData:
  access_key_id: $MY_LOKI_ACCESS_KEY_ID
  access_key_secret: $MY_LOKI_ACCESS_KEY_SECRET
  bucketnames: $MY_LOKI_BUCKETNAME
  endpoint: $MY_LOKI_ENDPOINT