apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: $VAR_OPERATORGROUP
  namespace: $VAR_NAMESPACE
  labels:
    backup.integration.ibm.com/component: $VAR_OPERATORGROUP  
spec:
  targetNamespaces:
  - $VAR_NAMESPACE  