apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: cluster-logging
  namespace: $MY_NAMESPACE
  labels:
    backup.integration.ibm.com/component: operatorgroup  
spec:
  targetNamespaces:
  - $MY_NAMESPACE