apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: $MY_POSTGRESQL_CLUSTER
  namespace: $MY_POSTGRESQL_NAMESPACE
spec:
  instances: 1
  storage:
    size: 1Gi
  image: quay.io/enterprisedb/postgresql:15  # Use PostgreSQL 15 image or compatible
  postgresql:
    parameters:
      shared_buffers: "128MB"
      max_connections: "100"
  bootstrap:
    initdb:
      database: $MY_POSTGRESQL_DATABASE
      owner: $MY_POSTGRESQL_USER
      secret:
        name: $MY_POSTGRESQL_SECRET
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            size: 1Gi
