apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: $MY_POSTGRESQL_CLUSTER
  namespace: $MY_POSTGRESQL_NAMESPACE
spec:
  description: $MY_POSTGRESQL_DATABASE_DESCRIPTION
  instances: 2
  storage:
    resizeInUseVolumes: true
    size: 1Gi
    storageClass: $MY_BLOCK_STORAGE_CLASS
  imagePullSecrets:
    - name: ibm-entitlement-key
  imageName: $MY_POSTGRESQL_IMAGE_NAME
#  imageName: 'icr.io/cpopen/edb/postgresql:15.8-1.22.5@sha256:63c1bfc431fba3eba7a2e803d5d24c48425dbe7d1e9b1dec9832b30717ce8753'
  enableSuperuserAccess: true
  logLevel: info
  startDelay: 3600
  stopDelay: 1800
  smartShutdownTimeout: 180
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  bootstrap:
    initdb:
      database: $MY_POSTGRESQL_DATABASE
      encoding: UTF8
      owner: $MY_POSTGRESQL_USER
#      secret:
#        name: $MY_POSTGRESQL_SECRET