apiVersion: v1
metadata:
  name: $VAR_PVC_NAME
  namespace: $VAR_PVC_NAMESPACE
kind: PersistentVolumeClaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: $VAR_PVC_STORAGE_CLASS
  volumeMode: Filesystem



