apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage
  namespace: openshift-image-registry
spec:
  storageClassName: ${MY_FILE_STORAGE_CLASS}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi