apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stepzen-to-graph-server-cert
  namespace: stepzen
spec:
  dnsNames:
  - stepzen.apps.${MY_CLUSTER_DOMAIN}
  isCA: true
  secretName: stepzen-to-graph-server-cert-secret
  issuerRef:
    name: ${MY_ISSUER}
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: graphql-to-graph-server-cert
  namespace: stepzen
spec:
  dnsNames:
#  - graphql.apps.${MY_CLUSTER_DOMAIN}
  - '*.apps.${MY_CLUSTER_DOMAIN}'
  isCA: true
  secretName: graphql-to-graph-server-cert-secret
  issuerRef:
    name: ${MY_ISSUER}
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: graphql-to-graph-server-subscriptions-cert
  namespace: stepzen
spec:
  dnsNames:
#  - graphql.apps.${MY_CLUSTER_DOMAIN}
  - '*.apps.${MY_CLUSTER_DOMAIN}'
  isCA: true
  secretName: graphql-to-graph-server-subscriptions-cert-secret
  issuerRef:
    name: ${MY_ISSUER}
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: introspection-cert
  namespace: stepzen
spec:
  dnsNames:
  - stepzen-introspection.apps.${MY_CLUSTER_DOMAIN}
  isCA: true
  secretName: introspection-cert-secret
  issuerRef:
    name: ${MY_ISSUER}
    kind: Issuer
