apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
  namespace: $MY_LOGGING_NAMESPACE
spec:
  type: Logging
  logging:
    lokiStack:
      name: $MY_LOKI_INSTANCE_NAME