apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${VAR_CERT}                             # ${TLS_ROOT_CERT_NAME}
  namespace: ${VAR_NAMESPACE}                   # ${TLS_NAMESPACE}
spec:
  commonName: ${VAR_COMMON_NAME}                # ${TLS_ROOT_CERT_NAME}
  duration: 17520h0m0s
  isCA: true
  issuerRef:
    kind: Issuer
    name: ${VAR_ISSUER}                         # ${TLS_CA_ISSUER_NAME}
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
    size: 2048
  renewBefore: 720h0m0s
  secretName: ${VAR_SECRET}                     # ${TLS_ROOT_CERT_NAME}
  secretTemplate:
    labels:
      app.kubernetes.io/component: ${VAR_LABEL} # ${TLS_LABEL1}
  usages:
  - key encipherment
  - digital signature