apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${VAR_CERT}                             # ${TLS_CERT_NAME}
  namespace: ${VAR_NAMESPACE}                   # ${TLS_NAMESPACE}
spec:
  commonName: ${VAR_COMMON_NAME}                # ${TLS_CERT_NAME}
  dnsNames:
  - ${VAR_CERT}.${VAR_INGRESS}                  # - ${TLS_CERT_NAME}.${TLS_INGRESS}
  duration: 17520h0m0s
  isCA: false
  issuerRef:
    kind: Issuer
    name: ${VAR_ISSUER}                         # ${TLS_CERT_ISSUER_NAME}
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
    size: 2048
  renewBefore: 720h0m0s
  secretName: ${VAR_SECRET}                     # ${TLS_CERT_NAME}
  secretTemplate:
    labels:
      app.kubernetes.io/component: ${VAR_LABEL} # ${TLS_LABEL1}
  usages:
  - server auth
  - client auth