apiVersion: v1
kind: ConfigMap
metadata:
  name: ${VAR_INI_CM}
  namespace: ${VAR_MQ_NAMESPACE}
data:
  config.ini: |-
    Service:
      Name=AuthorizationService
      EntryPoints=14
      SecurityPolicy=UserExternal
