apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${VAR_QMGR}-route
  namespace: $VAR_MQ_NAMESPACE
spec:
  host: ${VAR_CHL}.chl.mq.ibm.com
  to:
    kind: Service
    name: ${VAR_QMGR}-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough