apiVersion: v1
kind: ConfigMap
metadata:
  name: $VAR_AUTH_CM
  namespace: $VAR_MQ_NAMESPACE
data:
  ${VAR_QMGR_LC}.auth: |
    SET CHLAUTH(${VAR_QMGR_UC}CHL) TYPE(SSLPEERMAP) SSLPEER('CN=*') USERSRC(MAP) MCAUSER('${VAR_MQ_USER}') ACTION(ADD)
    * Define the user here
    SET AUTHREC PRINCIPAL('${VAR_MQ_USER}') OBJTYPE(QMGR) AUTHADD(ALL)
