apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: ${VAR_QMGR_LC}
  namespace: ${VAR_MQ_NAMESPACE}

spec:
  license:
    accept: true
    license: $MY_MQ_LIC
    use: NonProduction
  pki:
    keys:
      - name: ${VAR_QMGR_LC}
        secret:
          secretName: ${VAR_MQ_NAMESPACE}-mq-${VAR_QMGR_LC}-server-secret
          items:
            - tls.key
            - tls.crt
            - ca.crt
  queueManager:
    name: ${VAR_QMGR_LC}
    ini:
      - configMap:
          items:
          - config.ini
          name: ${VAR_INI_CM}
    mqsc:
      - configMap:
          name: ${VAR_MQSC_OBJECTS_CM}
          items:
          - ${VAR_QMGR_LC}.mqsc
      - configMap:
          name: ${VAR_AUTH_CM}
          items:
            - ${VAR_QMGR_LC}.auth
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      defaultClass: $MY_BLOCK_STORAGE_CLASS
      queueManager:
        type: persistent-claim
        size: 2Gi
      persistedData:
        enabled: true
      recoveryLogs:
        enabled: true
    availability:
      type: SingleInstance
  template:
    pod:
      containers:
        - env:
            - name: DEBUG
              value: 'false'
          name: qmgr
  version: $MY_MQ_VERSION
  web:
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
    manualConfig:
      configMap: 
        name: ${VAR_WEBCONFIG_CM}
    enabled: true