apiVersion: v1
kind: ConfigMap
metadata:
  name: $VAR_MQSC_OBJECTS_CM
  namespace: $VAR_MQ_NAMESPACE
data:
  ${VAR_QMGR_LC}.mqsc: |
    DEFINE CHANNEL('${VAR_QMGR_UC}CHL') CHLTYPE(SVRCONN) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') MCAUSER('${VAR_MQ_USER}') REPLACE
