apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: kafka-connect-credentials
  namespace: ${MY_OC_PROJECT}
  labels:
    eventstreams.ibm.com/cluster: ${es_instance}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    # permission to consume and produce to any topic
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - Write
          - Read
          - Create
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - Read
    type: simple