apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: cp4i-es
  name: cp4i-es-tn
spec:
  config:
    min.insync.replicas: "1"
    retention.ms: "86400000"
  partitions: 1
  replicas: 3
  topicName: cp4i-es-test