apiVersion: hsts.aspera.ibm.com/v1
kind: IbmAsperaHsts
metadata:
  namespace: $my_oc_project
  name: $my_cp_hsts_instance_name
spec:
  license:
    accept: true
    key: >-
$my_aspera_license_text
    use: CloudPakForIntegrationNonProduction
  deployments:
    default:
      replicas: 1
  version: $my_ibm_cp_hsts_version
  storages:
    - claimName: hsts-transfer-pvc
      class: ibmc-file-gold-gid
      deleteClaim: true
      mountPath: /data/
      size: 50Gi
  redis:
    persistence:
      enabled: false
      storageClass: ibmc-file-gold-gid
  services:
    httpProxy:
      type: ClusterIP
    tcpProxy:
      type: LoadBalancer
