apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${TLS_ROOT_CERT_NAME}
  namespace: ${TLS_NAMESPACE}
spec:
  commonName: ${TLS_ROOT_CERT_NAME}
  duration: 17520h0m0s
  isCA: true
  issuerRef:
    kind: Issuer
    name: ${TLS_CA_ISSUER_NAME}
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
    size: 2048
  renewBefore: 720h0m0s
  secretName: ${TLS_ROOT_CERT_NAME}
  secretTemplate:
    labels:
      app.kubernetes.io/component: ${TLS_LABEL1}
  usages:
  - key encipherment
  - digital signature