apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${TLS_CERT_NAME}
  namespace: ${TLS_NAMESPACE}
spec:
  commonName: ${TLS_CERT_NAME}
  dnsNames:
  - ${TLS_CERT_NAME}.${TLS_INGRESS}
  duration: 17520h0m0s
  isCA: false
  issuerRef:
    kind: Issuer
    name: ${TLS_CERT_ISSUER_NAME}
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
    size: 2048
  renewBefore: 720h0m0s
  secretName: ${TLS_CERT_NAME}
  secretTemplate:
    labels:
      app.kubernetes.io/component: ${TLS_LABEL1}
  usages:
  - server auth
  - client auth