apiVersion: v1
metadata:
  name: pvc-ldap-config
kind: PersistentVolumeClaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-file-bronze
  volumeMode: Filesystem
