apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: ace-paym-proc-api
  namespace: $MY_ACE_PROJECT
spec:
  license:
    accept: true
    license: $MY_ACE_LIC
    use: $MY_ACE_LIC_USAGE
  template:
    spec:
      containers:
        - name: runtime
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
  replicas: 1
  version: '12.0'
  barURL: 
    - >-
      https://github.com/prichelle/cp4i-demo-pr/raw/main/ace-bar-files/PaymentProcessAPI.bar
  configurations:
    - github-barauth
    - ace-policy-qm-mainmqm