apiVersion: appconnect.ibm.com/v1beta1
kind: DesignerAuthoring
metadata:
  name: ${VAR_ACE_DESIGNER_INSTANCE_NAME}
  namespace: $VAR_ACE_NAMESPACE
spec:
  license:
    accept: true
    license: $MY_ACE_LIC
    use: $MY_ACE_LIC_USAGE
  couchdb:
    storage:
      size: 10Gi
      type: persistent-claim
      class: $MY_BLOCK_STORAGE_CLASS
    replicas: 1
  designerMappingAssist:
    enabled: true
    incrementalLearning:
      schedule: Every 15 days
      storage:
        type: persistent-claim
        class: $MY_FILE_STORAGE_CLASS
      useIncrementalLearning: true
  designerFlowsOperationMode: local
  switchServer:
    name: ${VAR_ACE_SWITCHSERVER_INSTANCE_NAME}
#  authentication:
#    integrationKeycloak:
#      enabled: false
#  authorization:
#    integrationKeycloak:
#      enabled: false
  version: $MY_ACE_VERSION
  replicas: 2
