apiVersion: appconnect.ibm.com/v1beta1
kind: SwitchServer
metadata:
  name: ${VAR_ACE_SWITCHSERVER_INSTANCE_NAME}
  namespace: $VAR_ACE_NAMESPACE
spec:
  license:
    accept: true
    license: $MY_ACE_LIC
    use: $MY_ACE_LIC_USAGE
  logFormat: json
  version: $MY_ACE_VERSION