apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: $my_ibm_apic_instance_name
  namespace: $my_oc_project
spec:
  analytics:
    storage:
      enabled: true
      type: shared
  endpointTypes:
    - APIs
    - Events
  imagePullSecrets:
    - ibm-entitlement-key
  imageRegistry: cp.icr.io/cp/apic
  license:
    accept: true
    license: $my_ibm_apic_lic
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  profile: $my_ibm_apic_profile
  storageClassName: $my_block_storage_class
  version: $my_ibm_apic_version
