apiVersion: gateway.apiconnect.ibm.com/v1beta1
kind: GatewayCluster
metadata:
  name: ${VAR_APIC_INSTANCE_NAME}-gwv6
  namespace: ${VAR_APIC_NAMESPACE}
spec:
  version: ${MY_APIC_VERSION}
  profile: ${MY_APIC_PROFILE_GWV6}
  imagePullSecrets:
  - ${DEFAULT_IMAGE_PULL_SECRET}
  imageRegistry: ${MY_APIC_IMAGE_REGISTRY}
  apicGatewayServiceV5CompatibilityMode: false
  webGUIManagementPort: 9090
  webGUIManagementEnabled: true
  gatewayEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: rgw.${STACK_HOST}
      secretName: gwv6-endpoint
  gatewayManagerEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: rgwd.${STACK_HOST}
      secretName: gwv6-manager-endpoint
  apicGatewayServiceTLS:
    secretName: gateway-service
  apicGatewayPeeringTLS:
    secretName: gateway-peering
  mgmtPlatformEndpointCASecret:
    secretName: ${MY_APIC_TLS_INGRESS_CERT_NAME} # Usually ingress-ca
  #mgmtPlatformEndpointSvcCASecret:
  #  secretName:  # Usually management-ca
  datapowerLogLevel: 3
  license:
    accept: true
    use: nonproduction
    license: ${MY_APIC_LIC}
    metric: ${MY_APIC_METRIC}
  tokenManagementService:
    enabled: true
    storage:
      storageClassName: ${MY_BLOCK_STORAGE_CLASS}
      volumeSize: 30Gi
  adminUser:
    secretName: ${MY_DPGW_ADMIN_USER_SECRET}
  mtlsValidateClient: false
  # syslogConfig:
  #   enabled: false # if true, provide below details
  #   remoteHost: $DATAPOWER_SYSLOG_TCP_REMOTE_HOST # must be a string
  #   remotePort: $DATAPOWER_SYSLOG_TCP_REMOTE_PORT # must be an int
  #   secretName: $DATAPOWER_SYSLOG_TCP_TLS_SECRET # must be a string
