apiVersion: analytics.apiconnect.ibm.com/v1beta1
kind: AnalyticsCluster
metadata:
  name: ${VAR_APIC_INSTANCE_NAME}-a7s
  namespace: ${VAR_APIC_NAMESPACE}
  labels:
    app.kubernetes.io/instance: ${VAR_APIC_INSTANCE_NAME}-a7s
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: ${VAR_APIC_INSTANCE_NAME}-a7s
annotations:
    apiconnect-operator/cp4i: "false"
spec:
  version: ${MY_APIC_VERSION}
  apiAgentMode: true
  devPortalMode: true
  federatedAPIManagementMode: true
  license:
    accept: true
    use: nonproduction
    license: ${MY_APIC_LIC}
    metric: ${MY_APIC_METRIC}
  profile: ${MY_APIC_PROFILE_A7S}
  imagePullSecrets:
  - ${DEFAULT_IMAGE_PULL_SECRET}
  imageRegistry: ${MY_APIC_IMAGE_REGISTRY}
  mgmtPlatformEndpointCASecret:
    secretName: ${MY_APIC_TLS_INGRESS_CERT_NAME} # Usually ingress-ca
  mgmtPlatformEndpointSvcCASecret:
    secretName: ${MY_APIC_TLS_APIM_CERT_NAME} # Usually management-ca
  microServiceSecurity: certManager
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  ingestion:
    # enabled: true
    # clientAuthEnabled: true
    # configReloadAutomatic: true
    endpoint:
      #ingressClassName: $INGRESS_CLASS
      annotations:
        cert-manager.io/issuer: ingress-issuer
      hosts: 
      - name: ai.${STACK_HOST}
        secretName: analytics-ai-endpoint
    clientSubjectDN: CN=analytics-ingestion-client,O=cert-manager
  # mtlsValidateClient: true
  analyticsMode: true
  storage:
    enabled: true  
    type: ${MY_APIC_A7S_STORAGE_TYPE}
    shared:
      volumeClaimTemplate:
        storageClassName: ${OCP_BLOCK_STORAGE}
        volumeSize: ${MY_APIC_A7S_STORAGE_SIZE}