apiVersion: management.apiconnect.ibm.com/v1beta1
kind: ManagementCluster
metadata:
  labels:
    app.kubernetes.io/instance: management
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: ${VAR_APIC_INSTANCE_NAME}
  annotations:
    apiconnect-operator/cp4i: "false"    
  name: ${VAR_APIC_INSTANCE_NAME}-mgmt
  namespace: ${VAR_APIC_NAMESPACE}
spec:
  version: ${MY_APIC_VERSION}
  profile: ${MY_APIC_PROFILE_MGMT}
  imagePullSecrets:
  - ${DEFAULT_IMAGE_PULL_SECRET}
  imageRegistry: ${MY_APIC_IMAGE_REGISTRY}
  portal:
    admin:
      secretName: portal-admin-client
  analytics:
    ingestion:
      secretName: analytics-ingestion-client
  gateway:
    client:
      secretName: gateway-client-client
  devPortal:
    admin:
      secretName: devportal-admin-client
  wmAPIGateway:
    mgmt:
      secretName: wmapigateway-mgmt-client
  nanoGateway:
    mgmt:
      secretName: nano-gateway-mgmt-client
  federatedAPIManagement:
    admin:
      secretName: federatedapimanagement-admin-client
  cloudManagerEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
      haproxy.router.openshift.io/timeout: 240s
    hosts:
    - name: admin.${STACK_HOST}
      secretName: cm-endpoint
  apiManagerEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
      haproxy.router.openshift.io/timeout: 240s
    hosts:
    - name: manager.${STACK_HOST}
      secretName: apim-endpoint
  platformAPIEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
      haproxy.router.openshift.io/timeout: 240s
    hosts:
    - name: api.${STACK_HOST}
      secretName: api-endpoint
  consumerAPIEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
      haproxy.router.openshift.io/timeout: 240s
    hosts:
    - name: consumer.${STACK_HOST}
      secretName: consumer-endpoint
  adminUser:
    secretName: apic-mgmt-admin-pass
  consumerCatalogEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts: 
    - name: consumer-catalog.${STACK_HOST}
      secretName: consumer-catalog-endpoint
  databaseVolumeClaimTemplate:
    storageClassName: ${OCP_BLOCK_STORAGE}
  microServiceSecurity: certManager
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  license:
    accept: true
    use: nonproduction
    license: ${MY_APIC_LIC}
    metric: ${MY_APIC_METRIC}
  governance:
    enabled: true
  discovery:
    enabled: true
    proxyCollectorEnabled: true
    tablespaceDbVolumeClaimTemplate:
      storageClassName: ocs-external-storagecluster-ceph-rbd
      volumeSize: 25Gi