# Deploy Milvus Database 2.6.2.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: apic-ai-agent-milvus-db
  namespace: ${VAR_MILVUS_NAMESPACE}
  labels:
    app: milvus
spec:
  mode: standalone
  image: milvusdb/milvus:latest
  imagePullPolicy: IfNotPresent
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
          persistence:
            enabled: true
            storageClass: "${OCP_BLOCK_STORAGE}"
            size: 10Gi
    msgStreamType: kafka
    kafka:
      inCluster:
        deletionPolicy: Retain
        values:
          offsetsTopicReplicationFactor: 1
          zookeeper:
            enabled: true
            replicaCount: 1
          service:
            ports:
              client: 9092
            type: ClusterIP
          logRetentionHours: 168
          replicaCount: 1
          defaultReplicationFactor: 1
          persistence:
            enabled: true
            storageClass: "${OCP_BLOCK_STORAGE}"
            size: 10Gi
    storage:
      type: MinIO
      inCluster:
        values:
          mode: standalone
          replicaCount: 1
          resources:
            requests:
              memory: 1Gi
          deletionPolicy: Delete # or Retain
          pvcDeletion: true 
  components:
    serviceAccountName: "apic-ai-agent-milvus-db-kafka"
    standalone:
      serviceAccountName: "apic-ai-agent-milvus-db-kafka"
      serviceType: ClusterIP
      volumes:
      - name: milvus-tls
        secret:
          secretName: milvus-tls-secret
      volumeMounts:
      - name: milvus-tls
        mountPath: /milvus/tls
        readOnly: true
      nodeSelector: {}           # Optionally specify node labels
      tolerations: []            # Add tolerations if needed
      resources:
        requests:
          cpu: "2"
          memory: "8Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
      persistence:
        enabled: true
        storageClass: "${OCP_BLOCK_STORAGE}"
        size: 100Gi
  config:
    tls:
      serverPemPath: /milvus/tls/tls.crt
      serverKeyPath: /milvus/tls/tls.key
      caPemPath: /milvus/tls/ca.crt
      tlsMode: 1
    common:
      security:
        authorizationEnabled: true
        tlsMode: 1
        internaltlsEnabled: false
    log:
      level: "debug"
    proxy:
      http:
        enabled: false