apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations: 
    apiconnect-operator/backups-not-configured: "true"  
  name: $MY_APIC_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
spec:
  analytics:
    storage:
      enabled: true
      type: shared
  imagePullSecrets:
    - ibm-entitlement-key
  imageRegistry: cp.icr.io/cp/apic
  management:
    testAndMonitor:
      enabled: true
      aiEnabled: false
      autoTestEnabled: true
  license:
    accept: true
    license: $MY_APIC_LIC
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  profile: $MY_APIC_PROFILE
  storageClassName: $MY_BLOCK_STORAGE_CLASS
  version: $MY_APIC_VERSION
