apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations: 
    apiconnect-operator/backups-not-configured: "true"  
  name: ${VAR_APIC_INSTANCE_NAME}
  namespace: $VAR_APIC_NAMESPACE
spec:
  analytics:
    mtlsValidateClient: true
    storage:
      enabled: true
      type: shared
  imagePullSecrets:
    - ibm-entitlement-key
  imageRegistry: cp.icr.io/cp/apic
  management:
    testAndMonitor:
      enabled: true
      aiEnabled: false
      autoTestEnabled: true
    governance:
      enabled: true 
  portal:
    mtlsValidateClient: true
  gateway:
    webGUIManagementEnabled: true
  license:
    accept: true
    license: $MY_APIC_LIC
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  profile: $MY_APIC_PROFILE
  ai:
    enabled: true
    apiAgent:
      enabled: true
      vectorDatabaseSource: remote
      remoteVectorDatabase:
        type: milvus
        host: milvus.host
        port: 30279
        databaseName: default
        collectionName: apic_agent
        credentials: milvus-creds
  storageClassName: $MY_BLOCK_STORAGE_CLASS
  version: $MY_APIC_VERSION
