apiVersion: integration.ibm.com/v1beta1
kind: AssetRepository
metadata:
  name: $my_cp_ar_instance_name
  namespace: $my_oc_project
spec:
  license:
    accept: true
    license: $my_ibm_cp_ar_license
  replicas: 1
  storage:
    assetDataVolume:
      class: ibmc-file-gold-gid
    couchVolume:
      class: ibmc-block-gold
  version: $my_ibm_cp_ar_version
