kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: $VAR_FLINK_NAMESPACE
  name: ibm-flink-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: $MY_FILE_STORAGE_CLASS