kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: $my_oc_project
  name: ibm-flink-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: $my_file_storage_class