apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: $MY_EEM_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
spec:
  license:
    accept: true
    license: $MY_EEM_LIC
    metric: VIRTUAL_PROCESSOR_CORE
    use: $MY_EEM_LIC_USAGE
  manager:
    authConfig:
      authType: $MY_EEM_AUTH_TYPE
    storage: 
      storageClassName: $MY_FILE_STORAGE_CLASS 
      type: persistent-claim
    template:
      pod:
        spec:
          containers:
            - resources:
                limits:
                  cpu: '0.5'
                  memory: 512Mi
                requests:
                  cpu: '0.25'
                  memory: 256Mi
              name: manager
  version: $MY_EEM_VERSION