apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: $MY_EEM_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
spec:
  license:
    accept: true
    license: $MY_EEM_LIC
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    authConfig:
      authType: LOCAL
    storage: 
      storageClassName: $MY_FILE_STORAGE_CLASS 
      type: persistent-claim
  version: $MY_EEM_VERSION