apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: $MY_EGW_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
spec:
  license:
    accept: true
    license: $MY_EGW_LIC
    metric: VIRTUAL_PROCESSOR_CORE
    use: $MY_EG_LIC_USAGE
  managerEndpoint: $MY_EEM_MANAGER_GATEWAY_ROUTE
  gatewayGroupName: $MY_EGW_INSTANCE_GRP_NAME
  gatewayID: $MY_EGW_INSTANCE_NAME
  tls:
    caSecretName: ${MY_EEM_INSTANCE_NAME}-ibm-eem-manager-ca
  template:
    pod:
      spec:
        containers:
          - name: egw
            resources:
              requests:
                cpu: '0.5'
                memory: 512Mi
              limits:
                cpu: '1'
                memory: 1Gi
