apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: ${VAR_EGW_INSTANCE_NAME}
  namespace: $VAR_EGW_NAMESPACE
spec:
  license:
    accept: true
    license: $MY_EGW_LIC
    metric: VIRTUAL_PROCESSOR_CORE
    use: $MY_EGW_LIC_USAGE
  managerEndpoint: ${VAR_EEM_MANAGER_GATEWAY_ROUTE}
  gatewayGroupName: ${VAR_EGW_INSTANCE_GRP_NAME}
  gatewayID: ${VAR_EGW_INSTANCE_NAME}
  tls:
    caSecretName: ${VAR_EEM_INSTANCE_NAME}-ibm-eem-manager-ca
  template:
    pod:
      spec:
        containers:
          - name: egw
            resources:
              requests:
                cpu: '0.5'
                memory: 512Mi
              limits:
                cpu: '1'
                memory: 1Gi
