apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: $my_ibm_eg_instance_name
  namespace: $my_oc_project
spec:
  license:
    accept: true
    license: $my_ibm_egw_lic
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  managerEndpoint: $my_eem_manager_gateway_route
  gatewayGroupName: $my_ibm_eg_instance_grp_name
  gatewayID: $my_ibm_eg_instance_name
  tls:
    caSecretName: ${my_ibm_eem_instance_name}-ibm-eem-manager-ca
  template:
    pod:
      spec:
        containers:
          - name: egw
            resources:
              requests:
                cpu: '0.5'
                memory: 512Mi
              limits:
                cpu: '1'
                memory: 1Gi
