apiVersion: events.ibm.com/v1beta1
kind: EventProcessing
metadata:
  name: ${VAR_EP_INSTANCE_NAME}
  namespace: ${VAR_EP_NAMESPACE}
spec:
  license:
    accept: true
    license: $MY_EP_LIC
    use: $MY_EP_LIC_USAGE
  flink:
    endpoint: ${VAR_FLINK_INSTANCE_NAME}-rest.${VAR_EP_NAMESPACE}.svc.cluster.local:8081
  authoring:
    authConfig:
      authType: $MY_EP_AUTH_TYPE
    storage:
      type: persistent-claim
      storageClassName: $MY_FILE_STORAGE_CLASS