apiVersion: events.ibm.com/v1beta1
kind: EventProcessing
metadata:
  name: ${MY_EP_INSTANCE_NAME}
  namespace: ${MY_OC_PROJECT}
spec:
  license:
    accept: true
    license: $MY_EP_LIC
    use: $MY_EP_LIC_USAGE
  flink:
    endpoint: ${MY_FLINK_INSTANCE_NAME}-rest.${MY_OC_PROJECT}.svc.cluster.local:8081
  authoring:
    authConfig:
      authType: LOCAL
    storage:
      type: persistent-claim
      storageClassName: $MY_FILE_STORAGE_CLASS