apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  annotations:
    eventstreams.ibm.com/apicurio-registry-version: '>=2.4'
  name: cp4i-es
  namespace: cp4i
spec:
  version: latest
  license:
    license: L-YBXJ-ADJNSM
    accept: true
    use: CloudPakForIntegrationNonProduction
  requestIbmServices:
    iam: true
    monitoring: true
  strimziOverrides:
    entityOperator:
      topicOperator: {}
      userOperator: {}
    kafka:
      replicas: 3
      authorization:
        type: runas
      config:
        inter.broker.protocol.version: '3.5'
        offsets.topic.replication.factor: 3
      listeners:
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          tls: true
          type: internal
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: cp4i-es-metrics-config
      storage:
        type: persistent-claim
        class: ibmc-block-gold
        size: 10Gi
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: cp4i-es-metrics-config
      storage:
        type: persistent-claim
        class: ibmc-block-gold
        size: 4Gi
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}