apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: $MY_ES_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
spec:
  version: $MY_ES_VERSION
  license: 
    license: $MY_ES_LIC
    accept: true
    use: $MY_ES_LIC_USAGE
  strimziOverrides:
    entityOperator:
      topicOperator: {}
    kafka:
      replicas: 3
      authorization:
        type: simple
      config:
        default.replication.factor: 3
        inter.broker.protocol.version: '3.7'
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
        min.insync.replicas: 3
      listeners:
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: $MY_ES_METRICS_CM
      storage:
        type: persistent-claim
        class: $MY_BLOCK_STORAGE_CLASS
        size: 10Gi
    zookeeper:
      replicas: 1
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: $MY_ES_METRICS_CM
      storage:
        type: persistent-claim
        class: $MY_BLOCK_STORAGE_CLASS
        size: 4Gi
  adminApi: {}
  adminUI:
     authentication:
       - type: integrationKeycloak      
  apicurioRegistry: {}
  collector: {}
  restProducer: {}