apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: $MY_KEYCLOAK_REALM
  namespace: $VAR_KEYCLOAK_NAMESPACE
  labels:
    app: sso
spec:
  realm:
    id: $MY_KEYCLOAK_REALM
    realm: $MY_KEYCLOAK_REALM
    displayName: $MY_KEYCLOAK_REALM
    enabled: true  
  keycloakCRName: example-keycloak