apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  namespace: $MY_KEYCLOAK_NAMESPACE
  labels:
    app: sso
spec:
  instances: 1
  hostname:
    hostname: example.org
  http:
    tlsSecret: my-tls-secret