apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicenseServiceReporter
metadata:
  labels:
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/instance: ibmlicenseservicereporter-instance
    app.kubernetes.io/name: ibmlicenseservicereporter
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
  name: ${MY_LICENSE_SERVER_REPORTER_INSTANCE_NAME}
  namespace: ${MY_LICENSE_SERVER_NAMESPACE}
spec:
  license:
    accept: true
  authentication:
    useradmin:
      enabled: true
  storageClass: ${MY_BLOCK_STORAGE_CLASS}