kind: IBMLicensing
apiVersion: operator.ibm.com/v1alpha1
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
  name: $my_ibm_lic_srv_instance_name
spec:
  version: $MY_LICSRV_VERSION
  apiSecretToken: ibm-licensing-token
  datasource: datacollector
  httpsEnable: true