apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: $MY_LOKI_INSTANCE_NAME
  namespace: $MY_LOGGING_NAMESPACE
spec:
  managementState: Managed
  size: $MY_LOKI_PROFILE
  storage:
    schemas:
    - version: v13
      effectiveDate: "2024-12-01"
    secret:
      name: $MY_LOKI_SECRET
      type: s3
  storageClassName: $MY_BLOCK_STORAGE_CLASS
  tenants:
    mode: $MY_LOGGING_NAMESPACE