apiVersion: integration.ibm.com/v1beta1
kind: MessagingServer
metadata:
  name: ${VAR_MSGSRV_INSTANCE_NAME}
  namespace: $VAR_MQ_NAMESPACE
spec:
  license:
    accept: true
    license: $MY_MSGSRV_LIC
    use: $MY_MSGSRV_LIC_USAGE
  queueManager:
    storage:
      defaultClass: $MY_BLOCK_STORAGE_CLASS
    availability:
      type: SingleInstance
  version: $MY_MSGSRV_VERSION
---
apiVersion: integration.ibm.com/v1beta1
kind: MessagingQueue
metadata:
  name: ${VAR_MSGQ_INSTANCE_NAME}
  namespace: $VAR_MQ_NAMESPACE
spec:
  messagingServer:
    name: ${VAR_MSGSRV_INSTANCE_NAME}
  queue:
    name: ${VAR_MSGQ_INSTANCE_NAME}
    type: Local
---
apiVersion: integration.ibm.com/v1beta1
kind: MessagingChannel
metadata:
  name: ${VAR_MSGCHL_INSTANCE_NAME}
  namespace: $VAR_MQ_NAMESPACE
spec:
  messagingServer:
    name: ${VAR_MSGSRV_INSTANCE_NAME}
  channel:
    name: ${VAR_MSGSRV_INSTANCE_NAME}
    type: ServerConnMTLS
  sniRoute: 
    enabled: false
---
apiVersion: integration.ibm.com/v1beta1
kind: MessagingUser
metadata:
  name: ${VAR_MSGUSER_INSTANCE_NAME}
  namespace: $VAR_MQ_NAMESPACE
spec:
  user:
    name: ${VAR_MSGUSER_INSTANCE_NAME}
    channel:
      name: ${VAR_MSGCHL_INSTANCE_NAME}
    queues:
    - name: ${VAR_MSGQ_INSTANCE_NAME}
      auth: 
        - "PASSALL"