apiVersion: integration.ibm.com/v1beta1
kind: MessagingServer
metadata:
  name: $MY_MSGSRV_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
spec:
  license:
    accept: true
    license: $MY_MSGSRV_LIC
    use: $MY_MSGSRV_LIC_USAGE
  queueManager:
    storage:
      defaultClass: $MY_BLOCK_STORAGE_CLASS
    availability:
      type: SingleInstance
  version: $MY_MSGSRV_VERSION
---
apiVersion: integration.ibm.com/v1beta1
kind: MessagingQueue
metadata:
  name: $MY_MSGQ_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
spec:
  messagingServer:
    name: $MY_MSGSRV_INSTANCE_NAME
  queue:
    name: $MY_MSGQ_INSTANCE_NAME
    type: Local
---
apiVersion: integration.ibm.com/v1beta1
kind: MessagingChannel
metadata:
  name: $MY_MSGCHL_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
spec:
  messagingServer:
    name: $MY_MSGSRV_INSTANCE_NAME
  channel:
    name: $MY_MSGSRV_INSTANCE_NAME
    type: ServerConnMTLS
  sniRoute: 
    enabled: false
---
apiVersion: integration.ibm.com/v1beta1
kind: MessagingUser
metadata:
  name: $MY_MSGUSER_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
spec:
  user:
    name: $MY_MSGUSER_INSTANCE_NAME
    channel:
      name: $MY_MSGCHL_INSTANCE_NAME
    queues:
    - name: $MY_MSGQ_INSTANCE_NAME
      auth: 
        - "PASSALL"