apiVersion: v1
kind: ConfigMap
metadata:
  name: "${VAR_MQ_INSTANCE_NAME}-mqsc-cm"
  namespace: $VAR_MQ_NAMESPACE
data:
  ${VAR_QMGR}.mqsc: |
    DEFINE QLOCAL('Q1') REPLACE DEFPSIST(YES)
    DEFINE QLOCAL('PAYMT.REQ.CPY') REPLACE DEFPSIST(YES)
    DEFINE QLOCAL('FROM.KAFKA') REPLACE DEFPSIST(YES)
    DEFINE CHANNEL('${VAR_MQ_INSTANCE_NAME_UC}CHL') CHLTYPE(SVRCONN) REPLACE TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH('${VAR_MQ_INSTANCE_NAME_UC}CHL') TYPE(BLOCKUSER) USERLIST(NOBODY) ACTION(ADD)
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "${VAR_MQ_INSTANCE_NAME}_ROUTE"
  namespace: $VAR_MQ_NAMESPACE
spec:
  host: "${VAR_MQ_INSTANCE_NAME}chl.chl.mq.ibm.com"
  to:
    kind: Service
    name: ${VAR_MQ_INSTANCE_NAME}-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
---
apiVersion: v1
kind: Secret
metadata:
  name: "${VAR_MQ_INSTANCE_NAME}_SECRET"
  namespace: $VAR_MQ_NAMESPACE
data:
  tls.crt: $B64_QMGR_CRT
  tls.key: $B64_QMGR_KEY
  ca.crt: $B64_CA_CRT
type: kubernetes.io/tls
---
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $VAR_MQ_INSTANCE_NAME
  namespace: $VAR_MQ_NAMESPACE
spec:
  license:
    accept: true
    license: $MY_MQ_LIC
    use: NonProduction
  pki:
    keys:
      - name: $VAR_MQ_INSTANCE_NAME
        secret:
          secretName: "${VAR_MQ_INSTANCE_NAME}_SECRET"
          items:
            - tls.key
            - tls.crt
            - ca.crt
  queueManager:
    name: $VAR_MQ_INSTANCE_NAME_UC
    availability:
      type: SingleInstance
    mqsc:
      - configMap:
          name: "${VAR_MQ_INSTANCE_NAME}-mqsc-cm"
          items:
            - "${VAR_MQ_INSTANCE_NAME}.mqsc"
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: persistent-claim
        class: $MY_BLOCK_STORAGE_CLASS
        size: 2Gi
      defaultClass: $MY_BLOCK_STORAGE_CLASS
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: $MY_MQ_VERSION
  web:
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
      manualConfig:
        secret:
          name: cp4imq-web-secret
