apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: $MY_NAVIGATOR_INSTANCE_NAME
  namespace: $MY_OC_PROJECT
  labels:
    backup.integration.ibm.com/component: platformnavigator    
spec:
  license:
    accept: true
    license: $MY_NAVIGATOR_LIC
  replicas: 1
  version: $MY_NAVIGATOR_VERSION
