apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: ${MY_WLA_APP_NAME}
  namespace: ${MY_BACKEND_NAMESPACE}
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  serviceAccount:
    mountToken: true
  applicationImage: 'image-registry.openshift-image-registry.svc:5000/${MY_BACKEND_NAMESPACE}/${MY_WLA_APP_NAME_VERSION}'
  expose: true
  manageTLS: true
  replicas: 1
  pullPolicy: Always