kind: Secret
apiVersion: v1
metadata:
  name: cp4i-es--eem-user
  namespace: cp4i
  uid: 7aceb57e-a18b-4a0b-bc51-98542dc722e3
  resourceVersion: '19211044'
  creationTimestamp: '2023-10-04T07:05:09Z'
  labels:
    app: eem-demo-apis
    app.kubernetes.io/instance: cp4i-es--eem-user
    app.kubernetes.io/managed-by: strimzi-user-operator
    app.kubernetes.io/name: strimzi-user-operator
    app.kubernetes.io/part-of: eventstreams-cp4i-es--eem-user
    eventstreams.ibm.com/cluster: cp4i-es
    eventstreams.ibm.com/kind: KafkaUser
  ownerReferences:
    - apiVersion: eventstreams.ibm.com/v1beta2
      kind: KafkaUser
      name: cp4i-es--eem-user
      uid: 15fb0e30-be4d-4101-83ce-17b6794e3032
      controller: false
      blockOwnerDeletion: false
  managedFields:
    - manager: strimzi-user-operator
      operation: Update
      apiVersion: v1
      time: '2023-10-04T07:05:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:password': {}
          'f:sasl.jaas.config': {}
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:eventstreams.ibm.com/cluster': {}
            'f:eventstreams.ibm.com/kind': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"15fb0e30-be4d-4101-83ce-17b6794e3032"}': {}
        'f:type': {}
data:
  password: aUtDYnJqdjVBTDRlYjZ4V1JTT3BzVFBodUd0MkR6VmM=
  sasl.jaas.config: >-
    b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkuc2NyYW0uU2NyYW1Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT0iY3A0aS1lcy0tZWVtLXVzZXIiIHBhc3N3b3JkPSJpS0Nicmp2NUFMNGViNnhXUlNPcHNUUGh1R3QyRHpWYyI7
type: Opaque
