apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: quick-start-manager
spec:
  license:
    accept: false
    license: L-HRZF-DWHH7A
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral

