apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: apic-integration
spec:
  license:
    accept: true
    license: L-HRZF-DWHH7A
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
    template:
      pod:
        spec:
          containers:
            - name: manager
              resources:
                requests:
                  cpu: '0.25'
                  memory: 256Mi
                limits:
                  cpu: '0.5'
                  memory: 512Mi      
    apic:
      tls: false
      clientSubjectDN: 'CN=EEMCN,O=IBM,C=FR'
      jwks:
        endpoint: https://cpd-cp4i.cp4iad22023-b34dfa42ccf328c7da72e2882c1627b1-0000.eu-de.containers.appdomain.cloud/integration/apis/cp4i/cp4i-apic/api
