MY_USER=`whoami`
MY_USER_EMAIL=${MY_USER}@fr.ibm.com
MY_USER_ID="IAM#${MY_USER_EMAIL}"

# For Keycloak admin
MY_USER_PASSWORD=<one password you do not have to change it all the time>
MY_USER_FIRSTNAME=<First name>
MY_USER_LASTNAME=<your last name>

# For github connection with API Studio
MY_GITHUB_SERVER=https://github.com
MY_GITHUB_REPOSITORY=<your repository example ADesprets/apistudio>
MY_GIT_PAT_TOKEN=<your github PAT Token>

# For (20/09) TechZone access
MY_TECHZONE_USERNAME=kubeadmin
MY_TECHZONE_PASSWORD=<Password of kubeadmin, different each time a cluster is created>
MY_TECHZONE_OPENSHIFT_API_URL='<your API URL for the cluster example https://api.itz-a2xl6a.hub04-lb.techzone.ibm.com:6443'
