{
  "users": [
    {
      "username": "author1",
      "password": "Password1"
    },
    {
      "username": "viewer1",
      "password": "Password2"
    },
    {
      "username": "user1",
      "password": "Password1"
    }
  ]
}
