apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cloud-databases-redis-operator
  namespace: openshift-operators
spec:
  channel: $my_ibm_redis_operator_channel
  installPlanApproval: Automatic
  name: ibm-cloud-databases-redis-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
