apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sb2
  namespace: cp4i
spec:
  commonName: "*.67ce6e58c93eabd5dbaf02a8.ocp.techzone.ibm.com"
  dnsNames:
    - "*.67ce6e58c93eabd5dbaf02a8.ocp.techzone.ibm.com"
  duration: 8760h
  issuerRef:
    name: sb2-issuer
    kind: Issuer
  privateKey:
    algorithm: RSA
    size: 2048
  renewBefore: 720h
  secretName: sb2-secret
  subject:
    organizations:
      - "ibm"
    organizationalUnits:
      - "ibm_MQ"
  usages:
    - server auth
    - client auth
