apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sb2-route
  namespace: cp4i
spec:
  host: sb2chl.chl.mq.ibm.com
  to:
    kind: Service
    name: sb2-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough