kind: ConfigMap
apiVersion: v1
metadata:
  name: sb2-ldap-cm
  namespace: cp4i
data:
  sb2.ldap: |+
    *
    * setup LDAP
    *

    * define connection to LDAP server to use
    DEFINE AUTHINFO(USE.LDAP) +
    AUTHTYPE(IDPWLDAP) +
    CONNAME('ldap-service.ldap.svc.cluster.local(389)') +
    LDAPUSER('cn=admin,dc=ibm,dc=com') LDAPPWD('uLgH75o@At+9?zY0RBB') +
    SECCOMM(NO) +
    USRFIELD('uid') +
    SHORTUSR('uid') +
    BASEDNU('ou=people,dc=ibm,dc=com') +
    AUTHORMD(SEARCHGRP) +
    BASEDNG('ou=groups,dc=ibm,dc=com') +
    GRPFIELD('cn') +
    CLASSGRP('groupOfUniqueNames') +
    FINDGRP('uniqueMember') +
    REPLACE

    * configure the queue manager to use the LDAP connection for auth
    ALTER QMGR CONNAUTH(USE.LDAP)
    REFRESH QMGR TYPE(CONFIGEV) OBJECT(AUTHINFO)