apiVersion: v1
metadata:
  name: pvc-ldap-main
kind: PersistentVolumeClaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: example-storageclass
  volumeMode: Filesystem
