{
  "users": [
    {
      "username": "ep-admin",
      "password": "MyS3cr3tP1!"
    },
    {
      "username": "ep-viewer",
      "password": "MyS3cr3tP1!"
    },
    {
      "username": "user1",
      "password": "MyS3cr3tP1!"
    }
  ]
}
