{
  "mappings": [
    {
      "id": "ep-admin",
      "roles": [
        "author", "user"
      ]
    },
    {
      "id": "ep-viewer",
      "roles": [
        "viewer", "user"
      ]
    },
    {
      "id": "user1",
      "roles": [
        "user"
      ]
    }
  ]
}
