apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: es-admin
  labels:
    app.kubernetes.io/instance: ${es_instance}
    eventstreams.ibm.com/cluster: ${es_instance}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - operations:
          - Alter
          - DescribeConfigs
        resource:
          type: cluster
      - operations:
          - Create
          - Read
          - Write
          - Delete
          - DescribeConfigs
          - Alter
          - AlterConfigs
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operations:
          - Alter
          - Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - operations:
          - Read
          - Delete
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple