apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: ${es_instance}
    app.kubernetes.io/instance: ${es_instance}
  name: ${es_topic_name}
spec:
  config:
    min.insync.replicas: "1"
    retention.ms: "86400000"
  partitions: ${es_spec_topic_partition}
  replicas: ${es_spec_topic_replica}
  topicName: ${es_spec_topic_name}